In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/kaggle/input/datacsv/data.csv')

In [3]:
df.head()

x          y
0  48.955889  60.723602
1  44.687196  82.892504
2  60.297327  97.379897
3  45.618644  48.847153
4  38.816818  56.877213

In [4]:
x=df['x']
y=df['y']

In [5]:
x.head()

0    48.955889
1    44.687196
2    60.297327
3    45.618644
4    38.816818
Name: x, dtype: float64

# Linear Regression using Gredient Decent 

In [6]:
#initaially
m = 0
c = 0

learning_rate = 0.0001
n = int(len(x))


for i in range(100):
    pred = (m*x) + c
    der_m = (-2/n)*sum(x*(y-pred))
    der_c = (-2/n)*sum((y-pred))
    
    #update
    m = m-(learning_rate*der_m)
    c = c-(learning_rate*der_c)
    
print(m,c)

1.4809270431911752 0.03630800912185734


In [7]:
#y=mx+c
#y=1.4809270431911752*x + 0.03630800912185734

In [8]:
#initaially
m = 0
c = 0
learning_rate = 0.0001

n = int(len(x))

for i in range(100):
    pred = (m*x) + c
    der_m = (-2/n)*sum(x*(y-pred))
    der_c = (-2/n)*sum((y-pred))
    
    #update
    m = m-(learning_rate*der_m)
    c = c-(learning_rate*der_c)
    
    print(m,c)

0.7424335285442664 0.014629895049575754
1.1126970531591416 0.021962519495058154
1.2973530613155333 0.025655870599552186
1.3894434413955663 0.0275342538687902
1.4353697670010162 0.028507481513901093
1.4582732927878312 0.029029292372442533
1.4696949563898791 0.029325973726768786
1.4753904198682315 0.02951037889671325
1.4782301298722174 0.0296387897539973
1.4796456270098886 0.029739275026144867
1.4803508449518048 0.029825833065392132
1.4807018345728706 0.029905445088297247
1.4808761645055069 0.029981592746402
1.4809623912494785 0.03005601239860092
1.4810046794387284 0.030129569996634964
1.481025054728025 0.03020269740538055
1.481034501686347 0.030275610003205215
1.4810384985052363 0.03034841520296925
1.4810397772520703 0.03042116657329655
1.4810397004553588 0.03049389082977374
1.481038947631264 0.03056660129592062
1.4810378576660637 0.030639304616405304
1.4810365995681134 0.030712004105038864
1.4810352576247567 0.03078470141447726
1.481033873871527 0.030857397368930135
1.4810324692722603 

In [9]:
(m*48.955889)+c

72.53640795268723

# Least Square

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
reg=LinearRegression()

In [12]:
reg.fit(df[['x']], df[['y']])

LinearRegression()

In [13]:
reg.predict([[48.955889]])

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([[72.9323307]])

In [14]:
reg.coef_

array([[1.28735737]])

In [15]:
reg.intercept_

array([9.90860619])